#include "TestHelpers.h"
#include "heap.h"
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace WinAmyTests {

// Verification / hardening tests for the engine's Zobrist hashing on the 344-square
// 3D board. These lock in the conclusion that the existing 64-bit Zobrist scheme
// (hash_t = uint64_t) needs no change to remain collision-safe on the larger board:
//
//   1. Zobrist hashing never *guarantees* zero collisions (on any board size); it
//      makes them astronomically rare and the engine *tolerates* the rest.
//   2. The 344-square board introduces no new collision class: HashInit() draws an
//      independent 64-bit key for every (color, piece, square) via MT19937-64, so
//      collision odds depend on key width + nodes searched, not square count.
//   3. The engine accounts for collisions the standard way: a 32-bit TT signature,
//      LegalMove() re-validation of every hash move (so a collision can never play
//      an illegal move), and full-64-bit-key repetition detection.
//   4. No larger hash values are required for 344 squares.
//
// Test 1 guards against a future CBitBoard::SIZE change, a bad seed, or a generator
// regression silently producing duplicate keys (which would create *guaranteed*
// collisions). Test 2 confirms that, in practice, no two distinct positions reached
// during random self-play share the same 64-bit key.
TEST_CLASS(HashCollisionTests) {
  public:
    TEST_CLASS_INITIALIZE(InitializeEngine) {
        InitMoves();
        InitAll();
        HashInit();
        AllocateHT();
    }

    static uint32_t s_nRng;
    static uint32_t Rand() {
        s_nRng = s_nRng * 1664525u + 1013904223u;
        return s_nRng;
    }

    // Build a canonical, key-independent fingerprint of a position: full piece
    // placement on all squares plus side-to-move, castling rights and the
    // en-passant square. Two positions are "the same" iff their fingerprints match.
    static std::string BuildFingerprint(const CPosition *pPos) {
        std::string Fingerprint;
        Fingerprint.reserve(CBitBoard::SIZE + 6U);
        for (uint16_t nSquare = 0; nSquare < CBitBoard::SIZE; nSquare++) {
            Fingerprint.push_back(static_cast<char>(pPos->GetPiece(nSquare)));
        }
        Fingerprint.push_back(static_cast<char>(pPos->GetTurn()));
        Fingerprint.push_back(static_cast<char>(pPos->GetCastle()));
        const CSCoord &EnPassant = pPos->GetEnPassant();
        if (EnPassant.IsValid()) {
            uint16_t nOffset = EnPassant.BitOffset();
            Fingerprint.push_back(static_cast<char>(nOffset & 0xFFU));
            Fingerprint.push_back(static_cast<char>((nOffset >> 8) & 0xFFU));
        } else {
            Fingerprint.push_back(static_cast<char>(0xFF));
            Fingerprint.push_back(static_cast<char>(0xFF));
        }
        return Fingerprint;
    }

    // Every random 64-bit Zobrist key generated by HashInit() must be distinct.
    // Duplicate keys would XOR-cancel and produce guaranteed position collisions.
    TEST_METHOD(ZobristKeysAreDistinct) {
        std::unordered_set<hash_t> Keys;
        size_t nInserted = 0;

        for (int nColor = 0; nColor < 2; nColor++) {
            for (int nPiece = 0; nPiece < 8; nPiece++) {
                for (uint16_t nSquare = 0; nSquare < CBitBoard::SIZE; nSquare++) {
                    Keys.insert(HashKeys[nColor][nPiece][nSquare]);
                    nInserted++;
                }
            }
        }
        for (uint16_t nSquare = 0; nSquare < CBitBoard::SIZE; nSquare++) {
            Keys.insert(HashKeysEP[nSquare]);
            nInserted++;
        }
        for (int nIndex = 0; nIndex < 16; nIndex++) {
            Keys.insert(HashKeysCastle[nIndex]);
            nInserted++;
        }
        Keys.insert(STMKey);
        nInserted++;

        if (Keys.size() != nInserted) {
            std::ostringstream Os;
            Os << "Duplicate Zobrist keys detected: " << nInserted << " generated but only "
               << Keys.size() << " distinct";
            std::string Str = Os.str();
            std::wstring Wide(Str.begin(), Str.end());
            Assert::Fail(Wide.c_str());
        }
    }

    // Play many random legal games; map each visited position's 64-bit hash key to a
    // key-independent fingerprint. If the same key ever maps to a *different*
    // fingerprint, two distinct positions collided on the same 64-bit key.
    TEST_METHOD(NoFullKeyCollisionsOverRandomGames) {
        std::unordered_map<hash_t, std::string> SeenPositions;

        for (int nGame = 0; nGame < 60; nGame++) {
            s_nRng = 0x9E3779B1u + nGame * 2654435761u;
            PositionGuard Pos(CPosition::Initial());

            for (int nPly = 0; nPly < 80; nPly++) {
                hash_t HashKey = Pos.get()->GetHashKey();
                std::string Fingerprint = BuildFingerprint(Pos.get());

                auto Found = SeenPositions.find(HashKey);
                if (Found == SeenPositions.end()) {
                    SeenPositions.emplace(HashKey, Fingerprint);
                } else if (Found->second != Fingerprint) {
                    std::ostringstream Os;
                    Os << "Zobrist collision: key " << HashKey
                       << " maps to two distinct positions (game " << nGame << " ply " << nPly << ")";
                    std::string Str = Os.str();
                    std::wstring Wide(Str.begin(), Str.end());
                    Assert::Fail(Wide.c_str());
                }

                heap_t pHeap = allocate_heap();
                push_section(pHeap);
                Pos.get()->LegalMoves(pHeap);
                std::vector<CMove> Moves;
                for (unsigned int nI = pHeap->current_section->start;
                     nI < pHeap->current_section->end; ++nI) {
                    Moves.push_back(pHeap->data[nI]);
                }
                free_heap(pHeap);
                if (Moves.empty()) {
                    break;
                }
                CMove Move = Moves[Rand() % Moves.size()];
                Pos.get()->DoMove(Move);
            }
        }
    }
};

uint32_t HashCollisionTests::s_nRng = 1;

} // namespace WinAmyTests
